### ISSUE TITLE
Install Question?

### ISSUE THREAD

**Issue by jlhanson5** [bids-apps/BrainSuite#1]
Hello BrainSuite repo,

I was trying to test drive BrainSuite and ran into an error. I was originally getting a docker error when I put in the syntax specified on the front page of the repo (pasted below)...

`docker run -ti --rm \
  -v /home/jamielh/Volumes/Hanson/Pitt_PYS/BrainSuite/:/data \
  -v /home/jamielh/Volumes/Hanson/Pitt_PYS/BrainSuite/:/output \
  brainsuitebids \
  /data /output participant --participant_label 10044`

this output the following error:

`Unable to find image 'brainsuitebids:latest' locally
docker: Error response from daemon: repository brainsuitebids not found: does not exist or no pull access.
See 'docker run --help'.`

Googling around, I think the syntax should instead be:
`docker run -ti --rm \
-v /home/jamielh/Volumes/Hanson/Pitt_PYS/BrainSuite/:/data \
-v /home/jamielh/Volumes/Hanson/Pitt_PYS/BrainSuite/:/output \
bids/brainsuite \
/data /output participant --participant_label 10044`

* Note the change in the bids call (on the 4th line). I just thought I would post that in case others ran into that issue. 

Cheers,
Jamie.

**Comment by yeunkim** [comment]
Hi Jamie,

I apologize for the extremely late reply. Thank you for your input on the incorrect docker image name in the instructions. 
We have recently updated our BrainSuite BIDS App (to contain new software tools) as well as all documentation, which should be correct now. 

Thank you!
Yeun
