### ISSUE TITLE
CircleCI badge "failing" on bids-apps.neuroimaging.io/apps/ 

### ISSUE THREAD

**Issue by yeunkim** [bids-apps/BrainSuite#3]
Hi @Remi-Gau 

New release passed [CircleCI tests](https://app.circleci.com/pipelines/github/bids-apps/BrainSuite) but says it's failing on the badge on the [bids app website](https://bids-apps.neuroimaging.io/apps/).

**Comment by Remi-Gau** [comment]
I think this is because the badge looks at the status of the latest run of the workflow on master and not on tags.
And I had cancelled the latest run on master, so it shows as failed.

I re-triggered the run to update the badge and make sure it shows green.

**Comment by Remi-Gau** [comment]
fixed
